#!/usr/bin/env bash

HISTSIZE=100000
SAVEHIST=100000

export PATH="$HOME/.local/bin":$PATH

if [[ -n "$SSH_CLIENT" ]]; then
  export ZSH_MACHINE_NAME="${USER}@$(echo $SSH_CLIENT | awk '{print $1 ":" $3}')"
else
  export ZSH_MACHINE_NAME="local"
fi

if [ -f ~/.zsh_userenv ]; then
  source ~/.zsh_userenv
fi
